<?php

return [
    Webkul\Account\AccountPlugin::class,
    Webkul\Blog\BlogPlugin::class,
    Webkul\Chatter\ChatterPlugin::class,
    Modules\Crm\Services\ContactPlugin::class,
    Webkul\Employee\EmployeePlugin::class,
    Modules\Products\Services\InventoryPlugin::class,
    Webkul\Invoice\InvoicePlugin::class,
    Webkul\Product\ProductPlugin::class,
    Modules\Payments\Services\PaymentPlugin::class,
    Modules\Crm\Services\PartnerPlugin::class,
    Modules\Projects\Services\ProjectPlugin::class,
    Modules\Expenses\Services\PurchasePlugin::class,
    Webkul\Support\SupportPlugin::class,
    Webkul\Recruitment\RecruitmentPlugin::class,
    Modules\Invoices\Services\SalePlugin::class,
    Webkul\Security\SecurityPlugin::class,
    Webkul\Field\FieldsPlugin::class,
    Webkul\TimeOff\TimeOffPlugin::class,
    Webkul\FullCalendar\FullCalendarPlugin::class,
    Modules\Projects\Services\TimesheetPlugin::class,
    Webkul\Website\WebsitePlugin::class,
    Webkul\PluginManager\PluginManagerPlugin::class,
];
