<?php

return [
    Modules\Core\Services\AccountPlugin::class,
    Modules\Core\Services\BlogPlugin::class,
    Modules\Core\Services\ChatterPlugin::class,
    Modules\Crm\Services\ContactPlugin::class,
    Modules\Core\Services\EmployeePlugin::class,
    Modules\Products\Services\InventoryPlugin::class,
    Modules\Core\Services\InvoicePlugin::class,
    Modules\Core\Services\ProductPlugin::class,
    Modules\Payments\Services\PaymentPlugin::class,
    Modules\Crm\Services\PartnerPlugin::class,
    Modules\Projects\Services\ProjectPlugin::class,
    Modules\Expenses\Services\PurchasePlugin::class,
    Modules\Core\Services\SupportPlugin::class,
    Modules\Core\Services\RecruitmentPlugin::class,
    Modules\Invoices\Services\SalePlugin::class,
    Modules\Core\Services\SecurityPlugin::class,
    Modules\Core\Services\FieldsPlugin::class,
    Modules\Core\Services\TimeOffPlugin::class,
    Modules\Core\Services\FullCalendarPlugin::class,
    Modules\Projects\Services\TimesheetPlugin::class,
    Modules\Core\Services\WebsitePlugin::class,
    Modules\Core\Services\PluginManagerPlugin::class,
];
